"""empty message

Revision ID: cb449dca7863
Revises: 998fcede5c36
Create Date: 2017-10-27 21:52:53.780880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb449dca7863'
down_revision = '998fcede5c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_grade'), 'round', ['grade'], unique=False)
    op.create_table('comparing_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_color_id', sa.Integer(), nullable=False),
    sa.Column('second_color_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['second_color_id'], ['color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparing_colors_round_id'), 'comparing_colors', ['round_id'], unique=False)
    op.create_table('current_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_round_grade'), 'current_round', ['grade'], unique=True)
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comparing_colors_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparing_colors_id'], ['comparing_colors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    op.drop_index(op.f('ix_current_round_grade'), table_name='current_round')
    op.drop_table('current_round')
    op.drop_index(op.f('ix_comparing_colors_round_id'), table_name='comparing_colors')
    op.drop_table('comparing_colors')
    op.drop_index(op.f('ix_round_grade'), table_name='round')
    op.drop_table('round')
    # ### end Alembic commands ###
