"""empty message

Revision ID: d2ea6e9aa283
Revises: 
Create Date: 2017-09-08 16:40:17.843649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ea6e9aa283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_color', sa.String(length=64), nullable=True),
    sa.Column('background_color', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_background_color'), 'colors', ['background_color'], unique=False)
    op.create_index(op.f('ix_colors_text_color'), 'colors', ['text_color'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_colors_text_color'), table_name='colors')
    op.drop_index(op.f('ix_colors_background_color'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
